version: "3"
services:
  backend_user:
    build:
      context: ./udagram-api-user
    image: jptaba/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: jptaba/udagram-api-feed
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: jptaba/reverseproxy
  frontend:
    build:
      context: ./udagram-frontend
    image: jptaba/udagram-frontend