version: "3"
services:
  udagram-api-user:
    build:
      context: ./udagram-api-user
    image: jptaba/udagram-api-user
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
    image: jptaba/udagram-api-feed
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: jptaba/reverseproxy
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: jptaba/udagram-frontend