version: "3"
services:
  udagram-api-user:
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
    image: jptaba/udagram-api-user
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
    image: jptaba/udagram-api-feed
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
      dockerfile: Dockerfile
    image: jptaba/reverseproxy
  udagram-frontend:
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
    image: jptaba/udagram-frontend